name: FileExplorer
version: '${project.version}'
main: de.asedem.fileexplorer.FileExplorer
api-version: '1.20'

commands:
  dir:
    usage: /dir
    description: Lists all files and folders in a directory
