name: FileExplorer
version: '${project.version}'
main: de.asedem.fileexplorer.FileExplorer
api-version: '1.20'

commands:
  cd:
    usage: /cd [name]
    description: Let you move between directories
  rm:
    usage: /rm [name]
    description: Removed a file
  dir:
    usage: /dir
    description: Lists all files and folders in a directory
  pwd:
    usage: /pwd
    description: Shows you your current path
  mkdir:
    usage: /mkdir [folder names]
    description: Create Folders in your current directory
  reset:
    usage: /reset
    description: Resets your current directory and clears you clipboard
