name: FileExplorer
version: '${project.version}'
main: de.asedem.fileexplorer.FileExplorer
api-version: '1.20'

commands:
  cd:
    usage: /cd [name]
    description: Let you move between directories
  dir:
    usage: /dir
    description: Lists all files and folders in a directory
  pwd:
    usage: /pwd
    description: Shows you your current path
